-- Insertion du premier client
INSERT INTO customers (
    first_name,
    last_name,
    email,
    phone,
    password,
    profile_photo,
    date_of_birth,
    gender,
    address,
    city,
    country,
    id_card_number,
    id_card_type,
    account_status,
    email_verified,
    phone_verified,
    last_login
) VALUES (
    'Fatou',
    'Diallo',
    'fatou.diallo@gmail.com',
    '221775556677',
    'motdepasse123',
    NULL,
    '1990-05-15',
    'F',
    'Rue 12 x 13 Médina',
    'Dakar',
    'Sénégal',
    '1234567890123',
    'CNI',
    'active',
    TRUE,
    TRUE,
    '2025-02-10 15:30:00'
);

-- Insertion du deuxième client
INSERT INTO customers (
    first_name,
    last_name,
    email,
    phone,
    password,
    profile_photo,
    date_of_birth,
    gender,
    address,
    city,
    country,
    id_card_number,
    id_card_type,
    account_status,
    email_verified,
    phone_verified,
    last_login
) VALUES (
    'Moussa',
    'Sow',
    'moussa.sow@yahoo.fr',
    '221778889900',
    'password456',
    NULL,
    '1988-12-25',
    'M',
    'Villa 123, Almadies',
    'Dakar',
    'Sénégal',
    '9876543210987',
    'Passport',
    'active',
    TRUE,
    FALSE,
    '2025-02-11 09:15:00'
);
